### ISSUE TITLE
Routing in TYPO3 9.5.31 does not work - any ideas?

### ISSUE THREAD

**Issue by Shentao83** [nhovratov/jobfair#3]
Hey there, 

maybe I am just stupid, but I cant seem to get this to work. I feel like I am missing something:

```
  Jobfair:
    type: Extbase
    limitToPages:
      - 562
    extension: Jobfair
    plugin: Pi1
    routes:
      -
        routePath: '/{job_title}'
        _controller: 'Job::show'
        _arguments:
          job_title: job
    defaultController: 'Job::show'
    aspects:
      job_title:
        type: PersistedAliasMapper
        tableName: tx_jobfair_domain_model_job
        routeFieldName: slug
```
With this setup, the job list will be shown correctly with all the links. When I click on a link, I only see the homepage and not the job details. The link itself looks fine. If I replace _routeFieldName: slug_ with _routeFieldName: job_title_ the job details will be shown correclty, but the URL is not okay of course. 

Here is my setup:
TYPO3 9.5.31, Jobfair 3.0.1, Detail page has ID 562. All jobs have a slug generated.

The basically same routeEnhancer for tx_news does work though and I have no idea why it is not working...
